# This file was generated by the {rix} R package v0.12.4 on 2024-10-04
# with following call:
# >rix(r_ver = "frozen_edge",
#  > r_pkgs = NULL,
#  > system_pkgs = NULL,
#  > git_pkgs = list(list(package_name = "shinychat",
#  > repo_url = "https://github.com/jcheng5/shinychat",
#  > commit = "de2e7f92284c426a5f058c40c2623f38803dd05e"),
#  > list(package_name = "elmer",
#  > repo_url = "https://github.com/hadley/elmer",
#  > commit = "f272f745b5d96d0ad6198296024bbfc6222d272b")),
#  > ide = "code",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides bleeding
# edge packages and R.
# Only use bleeding edge packages if absolutely needed!
# Read more on https://docs.ropensci.org/rix/articles/z-bleeding_edge.html
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/3c171c130078f5717b5beed2f7aa48e593462dae.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      languageserver;
  };
 
  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "elmer";
      src = pkgs.fetchgit {
        url = "https://github.com/hadley/elmer";
        rev = "f272f745b5d96d0ad6198296024bbfc6222d272b";
        sha256 = "sha256-5hS7H7UVpKyiiwc80hZ+eUePZNTYWkji+vW2qJrZWtE=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          coro
          httr2
          jsonlite
          R6
          S7
          rlang
          shinychat;
      };
    })


    (pkgs.rPackages.buildRPackage {
      name = "shinychat";
      src = pkgs.fetchgit {
        url = "https://github.com/jcheng5/shinychat";
        rev = "de2e7f92284c426a5f058c40c2623f38803dd05e";
        sha256 = "sha256-F2V/SMiYEMaRD2lMoYfcDzAHbRMvTEZEdw6EyeP8olI=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          htmltools
          shiny
          coro;
      };
    })
   ];
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs rpkgs  system_packages   ];
  
}
